### ISSUE TITLE
Wifi name encoding error

### ISSUE THREAD

**Issue by CuneytTaha** [ushiboy/nmcli#43]
When I use the locale as "C" by setting the LANG environment variable, I can't properly encode some characters in the wifi name, so I can't connect to the wifi. But if I remove this parameter (env={'LANG': 'C'}) I can encode properly. Can you fixed this ?

for example;

my wifi name = "Cüneyt"

but my output = "C?neyt"

**Comment by ushiboy** [comment]
I'm sorry.
It is difficult to remove the LANG environment variable because the MODE and BARS of the execution result of the nmcli command will be different from the expectation depending on the system language setting.

**Comment by CuneytTaha** [comment]
I changed system environment like this :

`import locale`
`locale.setlocale(locale.LC_CTYPE, locale="tr_TR.UTF-8")`

but my problem is still persist, is this correct way to do it ? by the way im using ubuntu 20.04

**Comment by CuneytTaha** [comment]
if i use 'C.UTF-8':
`r = self._run(commands, capture_output=True, check=True, env={'LANG': 'C.UTF-8'})`
my problem solved. Will this cause any problems?

**Comment by ushiboy** [comment]
@CuneytTaha 
Please wait while I check and see.

**Comment by CuneytTaha** [comment]
OK, i am waiting. Thanks

**Comment by ushiboy** [comment]
As for SSID, it seems to be solved by using `C.UTF-8`.
However, I still have concerns about items such as MODE.
The following image is an example of running with `LANG=C.UTF-8` in an environment where the system language is `ja_JP.UTF-8`.
![image](https://user-images.githubusercontent.com/1749203/140593108-59a16491-875a-47c6-9f56-7ce34fc0d4e0.png)
![image](https://user-images.githubusercontent.com/1749203/140593119-4f4aec82-55b7-42c8-b14c-adfcb6bd7d8d.png)

As you can see in the image, the value of MODE is Japanese. This is not the value we are expecting.

My current idea is to add an API to make the LANG changeable from the default `C`.
For example, by executing `nmcli.set_lang('C.UTF-8')`, I think library users can get the value they expect for their individual environment to some extent.

(I'm not keen on making `C.UTF-8` the default because I can't read the full scope of the impact)

I plan to release the next version with this API in place.

**Comment by CuneytTaha** [comment]
That's exactly what I wanted the API to make LANG replaceable from default C. This is enough for me. I look forward to your releasing the next version. Thank you so much.

**Comment by ushiboy** [comment]
Thanks. Version 0.8.0 has been released, try it out.
