### ISSUE TITLE
wifi_connect 

### ISSUE THREAD

**Issue by KrrishnaShah** [ushiboy/nmcli#49]
nmcli.device.wifi_connect("ssid", "password123") does not return anything

what if somebody enters wrong password

I'm having issue with this

**Comment by ushiboy** [comment]
@KrrishnaShah
Thanks for the report!

Hmm, it looks like `nmcli device wifi connect` doesn't exit with an error even if the connection fails due to some error in the password.
The message `Error: Connection activation failed: (7) Secrets were required, but not provided.` is output to stdout, so I'll try to detect it and throw an exception.

**Comment by ushiboy** [comment]
@KrrishnaShah 
Please wait for a while until I release the next version with a fix for this problem.

**Comment by ushiboy** [comment]
@KrrishnaShah 
Version 1.0.0 has been released, try it out.
